feat: 게시글 수정, 삭제 기능 구현
Codeit-Sprint-6-Part3-Team6/Wikid pull request #24
Opened 2024-06-30 21:28 UTC by tabbyworld

제가 모든 기능을 한 브랜치에서 만들어버려서 나름 정리해서 올리고 있긴 한데, 
왜 이 코드가 여기있지? 싶거나 파일에는 보이지 않는 컴포넌트가 있는 부분이 있을 수도 있어요😭
의문있으신 부분 물어봐주시면 왜 그렇게 됐는지 바로 답변 드릴게요!

2024-07-01 08:15 UTC, hyunow requested changes

2024-07-01 08:15 UTC, hyunow commented on src/pages/addboard.tsx
> +      } catch (error) {
에러 처리 세세하게 해주셨네요 좋습니다 👍  저도 빨리 해야되는뎋

2024-07-01 08:15 UTC, hyunow commented on src/pages/addboard.tsx
> +            {articleContent.replace(/\s/g, "").length}자
글자수 세는 거 진짜 이상하네요 글자 스타일을 변경하면 같은 문장인데도 글자수가 달라져요....@.@

2024-07-01 10:02 UTC, tabbyworld commented on src/pages/addboard.tsx
> +            {articleContent.replace(/\s/g, "").length}자
그쵸 .. textEditor 컴포넌트를 건드리지 않고 하려면 이 방법 밖에 없는 것 같은데, 
이상하게 세어지니까 컴포넌트에서 뭔가 수정을 해야할 것 같아요🥹

2024-07-02 04:05 UTC, Kimyu94 approved these changes

2024-07-02 04:05 UTC, Kimyu94 commented on src/lib/api/articleApi.ts
> +  } catch (err: any) {
에러에도 타입 지정이 필요한건가요,,? 궁금!

2024-07-02 04:05 UTC, Kimyu94 commented on src/lib/api/articleApi.ts
> +      `/api/6-6/articles/${targetId}`,
baseURL이 `https://wikied-api.vercel.app/6-6/` 로 설정되어있는데 앞에 `/api/6-6/` 는 무슨 경로일까용?

2024-07-02 04:08 UTC, tabbyworld commented on src/lib/api/articleApi.ts
> +      `/api/6-6/articles/${targetId}`,
아 제가 cors 에러를 프록시 서버 설정하는 방법으로 해결했는데, 
그랬더니 baseURL 선언된 인스턴스를 사용하지 못하고 따로 프록시 서버에서 설정한 경로를 사용해야 하더라구욥🥲

근데 인스턴스 못쓰는 거 아까워서 저도 그냥 withcredentialsl 끄고 하는 방법으로 수정해야 할 것 같아요!

2024-07-02 04:10 UTC, tabbyworld commented on src/lib/api/articleApi.ts
> +  } catch (err: any) {
처음엔 지정하지 않았다가 지정해주라고 에러가 나서 지정했던 걸로 기억하는데.. 지금은 또 지워도 괜찮네욥..? 
한 번 다 지워봐야겠어욧

2024-07-02 04:13 UTC, hyunow approved these changes

2024-07-02 04:21 UTC, merged