feat: 댓글 등록, 수정, 삭제 기능 구현
Codeit-Sprint-6-Part3-Team6/Wikid pull request #25
Opened 2024-06-30 22:03 UTC by tabbyworld

제가 모든 기능을 한 브랜치에서 만들어버려서 나름 정리해서 올리고 있긴 한데,
왜 이 코드가 여기있지? 싶거나 파일에는 보이지 않는 컴포넌트가 있는 부분이 있을 수도 있어요😭
(전체 파일에는 포함되는 코드인데, 해당 커밋 단위와는 맞지 않을 수도 있는 코드들입니다)
의문있으신 부분 물어봐주시면 왜 그렇게 됐는지 바로 답변 드릴게요!

아마 이 브랜치가 가장 코드가 뒤섞여 있을 것 같은데요.. 
너무 리뷰하기가 어렵다 싶으시면 커밋 단위로 보시는 것보다 전체 파일로 보면 이해가 더 잘되실 것 같아요

2024-07-01 01:46 UTC, hyunow approved these changes
머지 되는지 체크

2024-07-01 03:32 UTC, hyunow requested changes

2024-07-01 03:32 UTC, hyunow commented on src/components/boards/CommentInput.tsx
> +      />
textarea에 focus 됐을 때 댓글 입력창 전체의 색을 바꾸려면 div태그에 focus-within 속성을 이용하면 좋아요!

<img width="1110" alt="image" src="https://github.com/Codeit-Sprint-6-Part3-Team6/Wikid/assets/112617546/f325d961-75de-4cc7-bd08-9174bcd3d4e8">
<img width="1110" alt="image" src="https://github.com/Codeit-Sprint-6-Part3-Team6/Wikid/assets/112617546/3e68d6a1-abad-4583-8983-c02d362c5098">
```
<div
      className={`${className} mx-auto flex min-h-[120px] w-full flex-wrap justify-end gap-[10px] rounded-lg bg-gray50 px-[15px] py-[13px] ring-gray200 focus-within:bg-white focus-within:ring-1`}
    >
      <textarea
        value={content}
        onChange={handleInputCount}
        placeholder="댓글을 입력해 주세요"
        maxLength={500}
        className="w-full rounded-md bg-gray50 p-1 ring-gray200 focus:bg-white"
      />
```

2024-07-01 03:32 UTC, hyunow commented on src/components/boards/CommentCard.tsx
> +        <div className="flex flex-col">
여기에 w-full 속성을 추가하면 사진처럼 input칸이 커집니당
<img width="1110" alt="image" src="https://github.com/Codeit-Sprint-6-Part3-Team6/Wikid/assets/112617546/ef2ecf7b-fd2e-4c3b-bb11-ab8e8ac0da79">

2024-07-01 03:44 UTC, tabbyworld commented on src/components/boards/CommentInput.tsx
> +      />
앗 이거 사실.. 일부러 텍스트가 입력되는 영역만 색이 다르면 좀 더 있어보이지 않을까..?! 싶어서 이렇게 해봤어용 ㅋㅋㅋㅋ 전 둘 다 좋아서 다른 팀원분들 의견도 여쭤보고 같이 정하면 좋을 것 같아요😆

2024-07-01 03:48 UTC, tabbyworld commented on src/components/boards/CommentCard.tsx
> +        <div className="flex flex-col">
와 지현님..!!! 진짜 너무너무 감사합니다😭🩷 십 년 묵은 체증이 싹 내려간 기분이네요 ,,
줄 수 있는 곳에는 w-full 다 줘봤다고 생각했는데 놓친 부분이 있었군요 ㅋㅋㅋㅋ ㅠㅠ

2024-07-01 22:40 UTC, MJY1993 approved these changes

2024-07-02 04:13 UTC, hyunow approved these changes

2024-07-02 04:15 UTC, Kimyu94 approved these changes

2024-07-02 04:22 UTC, merged